---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Découvrez les dernières modifications apportées aux fonctionnalités et aux services de données qui font partie du déploiement local de la NetApp Console. 
---
= Modifications récentes dans le déploiement local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie du déploiement local de NetApp Console.



[[21-september-2026]]
== 21 septembre 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.09* : Cette version inclut Trident Protect 26.09.
* Contrôle d'accès basé sur les rôles, granulaire au niveau du cluster et de l'espace de noms : lors de la découverte d'un cluster Kubernetes, vous pouvez contrôler l'accès aux ressources en sélectionnant un projet ou un dossier à associer au nouveau cluster. Vous pouvez également enregistrer des espaces de noms spécifiques pour le contrôle d'accès. Cela permet un contrôle d'accès plus granulaire au niveau du cluster ou de l'espace de noms.
* *Restauration de fichiers et de dossiers* : Vous pouvez désormais restaurer ou télécharger des fichiers et des dossiers spécifiques à partir de sauvegardes d'applications basées sur des machines virtuelles Kubernetes.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Découvrez comment protéger les charges de travail Kubernetes avec NetApp Backup and Recovery"].



[[16-september-2026]]
== 16 septembre 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Amélioration générale de la sauvegarde et de la restauration NetApp

Dans cette version, les charges de travail KVM, Hyper-V et VMware introduisent l'amélioration suivante :

*Sélection des informations d'identification lors de la découverte de l'hôte de machine virtuelle* : Lorsque vous découvrez un hôte KVM, Hyper-V ou VMware, vous pouvez désormais utiliser les informations d'identification que vous avez déjà ajoutées à Backup and Recovery.



==== Amélioration des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent l'amélioration suivante :

Protection étendue des disques pour les machines virtuelles : pour les configurations CIFS, NetApp Backup and Recovery prend désormais en charge la protection de chaque disque attaché à chaque machine virtuelle d'un groupe de protection. Cela inclut les fichiers répartis sur plusieurs volumes ONTAP ou systèmes de stockage ONTAP (disques étendus) ainsi que les fichiers limités à un seul emplacement.

Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Découvrez comment protéger les charges de travail Hyper-V avec NetApp Backup and Recovery"].



==== Amélioration des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent l'amélioration suivante en avant-première :

*Rapport quotidien de transfert de données de sauvegarde* : NetApp Backup and Recovery for Volumes inclut désormais un rapport quotidien de transfert de données de sauvegarde dans l’onglet Rapports, vous offrant une visibilité sur l’activité quotidienne de transfert de données de sauvegarde et de réplication au sein de votre environnement. Vous pouvez générer le rapport pour l’ensemble du compte ou pour des systèmes de stockage sélectionnés, filtrer par plage de dates et type de protection, et télécharger les résultats au format CSV.

Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Découvrez la protection des volumes ONTAP avec NetApp Backup and Recovery"].



[[17-august-2026]]
== 17 août 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent l'amélioration suivante :

*Restaurer la sauvegarde du stockage objet vers un emplacement alternatif* : Vous pouvez désormais restaurer les machines virtuelles Hyper-V, les fichiers et les dossiers du stockage objet vers un emplacement de stockage alternatif.

Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Découvrez comment protéger les charges de travail Hyper-V avec NetApp Backup and Recovery"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.08* : Cette version inclut Trident Protect 26.08.
* *Tentatives de sauvegarde* : Vous pouvez désormais activer les tentatives de sauvegarde et configurer le nombre de tentatives et les intervalles entre les tentatives en tant que paramètres avancés dans les politiques de protection Kubernetes.
* *Succès partiel de la sauvegarde* : Vous pouvez désormais configurer les paramètres avancés des politiques de protection Kubernetes pour poursuivre la sauvegarde en cas de défaillance de certaines ressources, ce qui permet aux tâches de sauvegarde de se terminer comme partiellement réussies. Cela vous permet de restaurer les ressources sauvegardées même si certaines ressources échouent pendant l’opération de sauvegarde.
* *Sauvegardes cohérentes avec le crash et cohérentes avec la VM* : le service Backup and Recovery for NetApp Console prend désormais en charge la configuration de politiques de protection qui créent des sauvegardes ou des snapshots cohérents avec le crash ou cohérents avec la VM. Vous pouvez également personnaliser la manière dont s'effectuent les gels de VM pendant l'opération de protection.
* *Reconnexion du cluster Kubernetes suite à un changement d'adresse IP de l'agent Console* : Le service Backup and Recovery for NetApp Console vous permet désormais de reconnecter un cluster à son agent Console si l'adresse IP de l'agent change.
* *Migration du cluster vers un nouvel agent Console* : Le service de sauvegarde et de récupération pour NetApp Console vous permet désormais de migrer un cluster vers un nouvel agent Console si l’agent d’origine tombe en panne ou est supprimé, garantissant ainsi une protection ininterrompue des applications.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Découvrez comment protéger les charges de travail Kubernetes avec NetApp Backup and Recovery"].



==== Amélioration des charges de travail Oracle Database

Cette version introduit les améliorations suivantes pour les charges de travail de la base de données Oracle :

* *Restauration de pluggable databases (PDB)* : Vous pouvez désormais restaurer des pluggable databases (PDB) individuelles et des espaces de tables PDB, y compris la récupération à un point précis dans le temps.
* *Clonage de base de données enfichable (PDB)* : Vous pouvez désormais cloner une seule PDB dans une base de données conteneur (CDB) existante, et éventuellement exclure des PDB lorsque vous clonez une base de données conteneur complète.


Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Découvrez comment protéger les charges de travail Oracle Database avec NetApp Backup and Recovery"].



[[10-august-2026]]
== 10 août 2026



[[netapp-console-local-deployment]]
=== NetApp Console déploiement local



==== Présentation du déploiement local de la NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Découvrez le déploiement local de NetApp Console"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Découvrez les différences entre le déploiement local de NetApp Console et NetApp Console SaaS et le mode privé"].



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations générales de NetApp Backup and Recovery

* *Prise en charge du déploiement local de la NetApp Console* : Cette version de NetApp Backup and Recovery prend en charge le déploiement local de la NetApp Console en version préliminaire.
* *Conservation des tâches pendant 90 jours* : NetApp Backup and Recovery conserve désormais les informations des tâches dans le Moniteur de tâches pendant 90 jours.




==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

* *Prise en charge de la restauration vers un emplacement alternatif pour les machines virtuelles SAN* : Vous pouvez désormais restaurer les sauvegardes de machines virtuelles SAN vers un emplacement alternatif.
* *Prise en charge de la suppression de plusieurs sauvegardes* : Vous pouvez désormais supprimer plusieurs sauvegardes à la fois.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Prise en charge préliminaire des ressources isolées* : Si vous exécutez NetApp Backup and Recovery dans le déploiement local de NetApp Console, vous pouvez découvrir, protéger et restaurer des ressources Kubernetes isolées. Cette fonctionnalité est en préversion pour cette version.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent les améliorations suivantes :

* *Prioriser les tâches de restauration par rapport aux sauvegardes* : Vous pouvez désormais donner la priorité aux tâches de restauration par rapport aux tâches de sauvegarde lors de la restauration de volumes, de fichiers ou de dossiers.
* *Découvrez les systèmes et volumes ONTAP sans activer Backup and Recovery* : Vous pouvez désormais découvrir les systèmes et volumes sans activer Backup and Recovery.


Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



[[13-july-2026]]
== 13 juillet 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Prise en charge améliorée de plusieurs compartiments pour toutes les charges de travail

NetApp Backup and Recovery prend désormais en charge la protection des charges de travail au sein d’un système comportant jusqu’à 100 compartiments répartis entre différents fournisseurs de cloud. ONTAP 9.19.1 ou une version ultérieure est requise pour prendre en charge plus de 6 compartiments par système.

Pour plus de détails sur NetApp Backup and Recovery, veuillez consulter https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Découvrez NetApp Backup and Recovery"].
