---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Découvrez les dernières modifications apportées aux fonctionnalités et aux services de données qui font partie du déploiement local de la NetApp Console. 
---
= Modifications récentes dans le déploiement local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux fonctionnalités et aux services de données qui font partie du déploiement local de NetApp Console.



[[17-august-2026]]
== 17 août 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent l'amélioration suivante :

*Restaurer la sauvegarde du stockage objet vers un emplacement alternatif* : Vous pouvez désormais restaurer les machines virtuelles Hyper-V, les fichiers et les dossiers du stockage objet vers un emplacement de stockage alternatif.

Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Découvrez comment protéger les charges de travail Hyper-V avec NetApp Backup and Recovery"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.08* : Cette version inclut Trident Protect 26.08.
* *Tentatives de sauvegarde* : Vous pouvez désormais activer les tentatives de sauvegarde et configurer le nombre de tentatives et les intervalles entre les tentatives en tant que paramètres avancés dans les politiques de protection Kubernetes.
* *Succès partiel de la sauvegarde* : Vous pouvez désormais configurer les paramètres avancés des politiques de protection Kubernetes pour poursuivre la sauvegarde en cas de défaillance de certaines ressources, ce qui permet aux tâches de sauvegarde de se terminer comme partiellement réussies. Cela vous permet de restaurer les ressources sauvegardées même si certaines ressources échouent pendant l’opération de sauvegarde.
* *Sauvegardes cohérentes avec le crash et cohérentes avec la VM* : le service Backup and Recovery for NetApp Console prend désormais en charge la configuration de politiques de protection qui créent des sauvegardes ou des snapshots cohérents avec le crash ou cohérents avec la VM. Vous pouvez également personnaliser la manière dont s'effectuent les gels de VM pendant l'opération de protection.
* *Reconnexion du cluster Kubernetes suite à un changement d'adresse IP de l'agent Console* : Le service Backup and Recovery for NetApp Console vous permet désormais de reconnecter un cluster à son agent Console si l'adresse IP de l'agent change.
* *Migration du cluster vers un nouvel agent Console* : Le service de sauvegarde et de récupération pour NetApp Console vous permet désormais de migrer un cluster vers un nouvel agent Console si l’agent d’origine tombe en panne ou est supprimé, garantissant ainsi une protection ininterrompue des applications.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Découvrez comment protéger les charges de travail Kubernetes avec NetApp Backup and Recovery"].



==== Amélioration des charges de travail Oracle Database

Cette version introduit les améliorations suivantes pour les charges de travail de la base de données Oracle :

* *Restauration de pluggable databases (PDB)* : Vous pouvez désormais restaurer des pluggable databases (PDB) individuelles et des espaces de tables PDB, y compris la récupération à un point précis dans le temps.
* *Clonage de base de données enfichable (PDB)* : Vous pouvez désormais cloner une seule PDB dans une base de données conteneur (CDB) existante, et éventuellement exclure des PDB lorsque vous clonez une base de données conteneur complète.


Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Découvrez comment protéger les charges de travail Oracle Database avec NetApp Backup and Recovery"].



[[10-august-2026]]
== 10 août 2026



[[netapp-console-local-deployment]]
=== NetApp Console déploiement local



==== Présentation du déploiement local de la NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Découvrez le déploiement local de NetApp Console"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Découvrez les différences entre le déploiement local de NetApp Console et NetApp Console SaaS et le mode privé"].



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations générales de NetApp Backup and Recovery

* *Prise en charge du déploiement local de la NetApp Console* : Cette version de NetApp Backup and Recovery prend en charge le déploiement local de la NetApp Console en version préliminaire.
* *Conservation des tâches pendant 90 jours* : NetApp Backup and Recovery conserve désormais les informations des tâches dans le Moniteur de tâches pendant 90 jours.




==== Améliorations des charges de travail VMware

Dans cette version, VMware workloads introduit les améliorations suivantes :

* *Prise en charge de la restauration vers un emplacement alternatif pour les machines virtuelles SAN* : Vous pouvez désormais restaurer les sauvegardes de machines virtuelles SAN vers un emplacement alternatif.
* *Prise en charge de la suppression de plusieurs sauvegardes* : Vous pouvez désormais supprimer plusieurs sauvegardes à la fois.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Prise en charge préliminaire des ressources isolées* : Si vous exécutez NetApp Backup and Recovery dans le déploiement local de NetApp Console, vous pouvez découvrir, protéger et restaurer des ressources Kubernetes isolées. Cette fonctionnalité est en préversion pour cette version.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent les améliorations suivantes :

* *Prioriser les tâches de restauration par rapport aux sauvegardes* : Vous pouvez désormais donner la priorité aux tâches de restauration par rapport aux tâches de sauvegarde lors de la restauration de VMs ou de fichiers.
* *Découvrez les systèmes et volumes ONTAP sans activer Backup and Recovery* : Vous pouvez désormais découvrir les systèmes et volumes sans activer Backup and Recovery.


Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



[[13-july-2026]]
== 13 juillet 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Prise en charge améliorée de plusieurs compartiments pour toutes les charges de travail

NetApp Backup and Recovery prend désormais en charge la protection des charges de travail au sein d’un système comportant jusqu’à 100 compartiments répartis entre différents fournisseurs de cloud. ONTAP 9.19.1 ou une version ultérieure est requise pour prendre en charge plus de 6 compartiments par système.

Pour plus de détails sur NetApp Backup and Recovery, veuillez consulter https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Découvrez NetApp Backup and Recovery"].



[[15-june-2026]]
== 15 juin 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail Kubernetes

Cette version introduit les améliorations suivantes pour les charges de travail Kubernetes :

* *Trident Protect 26.06* : Cette version inclut Trident Protect 26.06.
* *Ignorer la création d'applications lors de la restauration* : Vous pouvez désormais ignorer la création automatique d'objets de ressources personnalisés d'application lors des opérations de restauration. Cela réduit les entrées inutiles dans l’inventaire des applications.
* *Restauration des volumes persistants de machines virtuelles* : Lors de la restauration d’applications basées sur des machines virtuelles, vous pouvez désormais restaurer des volumes persistants individuels sans restaurer l’intégralité de la machine virtuelle, ce qui accélère la récupération lorsque des disques ou des volumes spécifiques sont affectés par une corruption ou une perte de données.
* *Améliorations du suivi des tâches* : Le suivi des tâches offre désormais une meilleure visibilité sur les tâches de protection Kubernetes. Vous pouvez consulter des informations d'état détaillées sur les tâches et sous-tâches, et voir le stockage cible utilisé par chacune.


Pour plus de détails sur la protection des charges de travail Kubernetes, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Vue d'ensemble de la protection des workloads Kubernetes"].



[[08-june-2026]]
== 08 juin 2026



[[backup-and-recovery]]
=== Sauvegarde et récupération



==== Améliorations des charges de travail des volumes ONTAP

Dans cette version, les charges de travail ONTAP Volumes introduisent l'amélioration suivante :

*Prise en charge du stockage cloud compatible S3* : NetApp Backup and Recovery pour les charges de travail Volumes prend désormais en charge la sauvegarde vers un stockage cloud compatible S3.

Pour plus de détails sur la protection des charges de travail ONTAP Volumes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Présentation de la protection des charges de travail ONTAP Volumes"].



==== Améliorations des charges de travail Hyper-V

Dans cette version, les charges de travail Hyper-V introduisent les améliorations suivantes :

* *Améliorations concernant la restauration de fichiers et de dossiers sur une machine virtuelle invitée* : Vous pouvez désormais restaurer des fichiers et des dossiers à partir d’un instantané sur un stockage principal ou secondaire vers une machine virtuelle Windows invitée. Cette fonctionnalité est désormais prise en charge pour les VM CIFS et SAN.
* *Les groupes de protection utilisent désormais la planification du fuseau horaire de l'hôte* : Les groupes de protection utilisent désormais le fuseau horaire de l'hôte Hyper-V. Les groupes de protection créés avant l'introduction de la planification basée sur le fuseau horaire de l'hôte continuent d'utiliser leur heure précédemment configurée (généralement UTC). Pour mettre à jour ces groupes de protection afin qu'ils utilisent le fuseau horaire de l'hôte Hyper-V, vous devez recréer les planifications. Consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail Hyper-V"] pour plus d'informations.


Pour plus de détails sur la protection des charges de travail Hyper-V, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Flux de travail de protection Hyper-V avec NetApp Backup and Recovery"].



==== Améliorations des charges de travail VMware

Dans cette version, les charges de travail VMware introduisent l'amélioration suivante :

* *Les groupes de protection utilisent désormais la planification selon le fuseau horaire de l’hôte* : les groupes de protection utilisent désormais le fuseau horaire du serveur VMware vCenter hôte. Les groupes de protection créés avant l’introduction de la planification selon le fuseau horaire de l’hôte continuent de fonctionner selon leur fuseau horaire précédemment configuré (généralement UTC). Pour utiliser le fuseau horaire de vCenter, vous devez recréer les planifications. Consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail VMware"] pour plus d'informations.


Pour plus de détails sur la protection des charges de travail VMware, consultez  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Vue d'ensemble de la protection des workloads VMware"].
